/**
 * OptiShare Transfer Pipeline Constants
 */

export const PIPELINE_CONFIG = {
  DEFAULT_SYMBOL_SIZE: 512,
  DEFAULT_FPS: 15,
  DEFAULT_WATCHDOG_TIMEOUT_MS: 15000,
  DEFAULT_REDUNDANCY_FACTOR: 1.35,
  DEFAULT_REPLAY_WINDOW_SIZE: 1024,
  METADATA_ANNOUNCE_INTERVAL_FRAMES: 15,
} as const;

export enum PipelineStageId {
  FILE_INPUT = 'FILE_INPUT',
  ENCRYPTION = 'ENCRYPTION',
  CHUNKING = 'CHUNKING',
  FOUNTAIN_ENCODE = 'FOUNTAIN_ENCODE',
  FRAMING = 'FRAMING',
  VALIDATION = 'VALIDATION',
  FOUNTAIN_DECODE = 'FOUNTAIN_DECODE',
  DECRYPTION = 'DECRYPTION',
  RECONSTRUCTION = 'RECONSTRUCTION',
}

export enum PipelineStatus {
  IDLE = 'IDLE',
  INITIALIZING = 'INITIALIZING',
  RUNNING = 'RUNNING',
  PAUSED = 'PAUSED',
  FINALIZING = 'FINALIZING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  ERROR = 'ERROR',
}

export enum PipelineErrorCode {
  INITIALIZATION_FAILED = 'INITIALIZATION_FAILED',
  STAGE_EXECUTION_FAILED = 'STAGE_EXECUTION_FAILED',
  ENCRYPTION_FAILED = 'ENCRYPTION_FAILED',
  DECRYPTION_FAILED = 'DECRYPTION_FAILED',
  INTEGRITY_CHECK_FAILED = 'INTEGRITY_CHECK_FAILED',
  TIMEOUT = 'TIMEOUT',
  CANCELLED = 'CANCELLED',
  INVALID_FRAME = 'INVALID_FRAME',
  REPLAY_ATTACK_DETECTED = 'REPLAY_ATTACK_DETECTED',
  SESSION_MISMATCH = 'SESSION_MISMATCH',
  FILE_READ_FAILED = 'FILE_READ_FAILED',
  FILE_WRITE_FAILED = 'FILE_WRITE_FAILED',
}
