/**
 * OptiShare Transfer Engine Constants
 */

export enum TransferEngineState {
  IDLE = 'IDLE',
  PREPARING = 'PREPARING',
  HANDSHAKING = 'HANDSHAKING',
  TRANSFERRING = 'TRANSFERRING',
  PAUSED = 'PAUSED',
  FINALIZING = 'FINALIZING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

export enum TransferMode {
  STANDARD = 'standard',
  FOUNTAIN = 'fountain',
}

export enum TransferRole {
  SENDER = 'sender',
  RECEIVER = 'receiver',
}

export enum TransferErrorCode {
  SESSION_NOT_INITIALIZED = 'SESSION_NOT_INITIALIZED',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  CHECKSUM_MISMATCH = 'CHECKSUM_MISMATCH',
  TIMEOUT = 'TIMEOUT',
  USER_CANCELLED = 'USER_CANCELLED',
  DECODING_FAILED = 'DECODING_FAILED',
  FILE_WRITE_FAILED = 'FILE_WRITE_FAILED',
  FILE_READ_FAILED = 'FILE_READ_FAILED',
  MAX_RETRIES_EXCEEDED = 'MAX_RETRIES_EXCEEDED',
  CORRUPT_FRAME = 'CORRUPT_FRAME',
}

export const TRANSFER_CONFIG = {
  DEFAULT_CHUNK_SIZE: 256,
  DEFAULT_FRAME_RATE_FPS: 15,
  MIN_FRAME_RATE_FPS: 1,
  MAX_FRAME_RATE_FPS: 60,
  DEFAULT_INACTIVITY_TIMEOUT_MS: 10000,
  METRICS_EMA_ALPHA: 0.2,
  DEFAULT_MAX_RETRIES: 3,
  DEFAULT_FOUNTAIN_REDUNDANCY_FACTOR: 1.3,
  METRICS_UPDATE_INTERVAL_MS: 200,
} as const;
