/**
 * OptiShare Security & Encryption Constants
 */

export const SECURITY_CONFIG = {
  AES_KEY_SIZE_BYTES: 32, // 256 bits
  AES_KEY_SIZE_BITS: 256,
  GCM_IV_SIZE_BYTES: 12, // 96-bit standard GCM nonce
  GCM_TAG_SIZE_BYTES: 16, // 128-bit authentication tag
  SALT_SIZE_BYTES: 16, // 128-bit HKDF salt
  DEFAULT_REPLAY_WINDOW_SIZE: 1024,
  MAX_STREAMING_CHUNK_SIZE_BYTES: 65536, // 64 KB
} as const;

export const CRYPTO_ALGORITHMS = {
  CIPHER: 'AES-GCM',
  ECDH_CURVE: 'P-256',
  HKDF_HASH: 'SHA-256',
  DIGEST_HASH: 'SHA-256',
} as const;

export enum SecurityErrorCode {
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  REPLAY_ATTACK_DETECTED = 'REPLAY_ATTACK_DETECTED',
  INVALID_KEY_LENGTH = 'INVALID_KEY_LENGTH',
  INVALID_IV_LENGTH = 'INVALID_IV_LENGTH',
  KEY_EXCHANGE_FAILED = 'KEY_EXCHANGE_FAILED',
  CORRUPTED_CIPHERTEXT = 'CORRUPTED_CIPHERTEXT',
  EXPIRED_SESSION_KEY = 'EXPIRED_SESSION_KEY',
  TAMPERED_DATA = 'TAMPERED_DATA',
  CRYPTO_OPERATION_FAILED = 'CRYPTO_OPERATION_FAILED',
}
